name: Manual Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags, required for Lerna (default is 1)
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Build Packages
        run: |
          corepack enable
          pnpm install
          npx lerna run build --ignore "@versini/example-*" --ignore @versini/documentation --ignore @versini/bundlesize

      - name: Publish Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        run: |
          corepack enable
          npx lerna publish from-package --no-push --no-private --yes --loglevel debug
