name: Manual Bump

on: workflow_dispatch

jobs:
  release-bundlesize:
    if: false # temporarily disabled <<<<<=======================
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      # secrets.GITHUB_TOKEN is used by default with "checkout",
      # but in this case we are explicitely using a personal
      # token with the same permissions (NODE_CLI).
      # This is because we want to use the "release-please" action
      # that updates and commit files. Other jobs should react to
      # these commits and run.
      # From GitHub docs: "When you use the repository's GITHUB_TOKEN
      # to perform tasks on behalf of the GitHub Actions app, events
      # triggered by the GITHUB_TOKEN will not create a new workflow
      # run. This prevents you from accidentally creating recursive
      # workflow runs.
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NODE_CLI }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run build --ignore "@versini/example-*" --ignore @versini/documentation
          npx lerna run stats:release
      - name: Commit Release Stats
        uses: stefanzweifel/git-auto-commit-action@v5

  bump:
    # needs: release-bundlesize - temporarily disabled <<<<<=======================
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      # packages: "write"
      # actions: "read"
    # permissions: write-all

    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BUMP_AND_RELEASE_APPID }}
          private-key: ${{ secrets.BUMP_AND_RELEASE_SECRET }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags, required for Lerna (default is 1)
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Version Bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          corepack enable
          git config user.name "aversini"
          git config user.email "versini@gmail.com"

          npx lerna version --exact --conventional-commits --create-release github --no-private --yes
