name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

env:
  COREPACK_ENABLE_STRICT: 0

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run build --ignore "@versini/example-*" --ignore @versini/documentation
          npx lerna run stats:pr
          npx lerna run stats:report
      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: |
            packages/ui-components/tmp/pr-stats.md
            packages/ui-fingerprint/tmp/pr-stats.md
            packages/ui-form/tmp/pr-stats.md
            packages/ui-system/tmp/pr-stats.md

  inspect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run lint --ignore @versini/documentation
          npx lerna run build --ignore @versini/documentation
          npx lerna run test:coverage --ignore @versini/documentation
