name: "size"
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable
      - run: yarn set version berry
      - run: yarn install
      - run: npx lerna run build
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/bundlesize
          package_manager: yarn
          skip_step: install
